### ISSUE TITLE
Feature proposal: A way to load specific secret as pod's environment variable.

### ISSUE THREAD

**Issue by nilevols** [mss-boot-io/cd-template#3]
**Background:**

My application needs to use an API key from the environment variable, this API key should be considered sensitive information, like a secret.

**Feature Description:**

The secret information should be set "secretly", and be loaded as an environment variable when declared in `deploy-config.yml`.

**Comment by lwnmengjing** [comment]
done

**Comment by lwnmengjing** [comment]
supported
